{{- if .Values.kubeconfigSecretName }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:multicluster-controlplane:license-proxyserver
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"  # This grants aggregation
rules:
  # Get cluster id
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs: ["get"]
  # ocm cluster claim
  - apiGroups:
    - cluster.open-cluster-management.io
    resources:
    - clusterclaims
    verbs: ["get", "create", "update"]
  - apiGroups:
      - apiregistration.k8s.io
    resources:
      - apiservices
    verbs: [ "*" ]
{{- end }}